# Site settings
title: *sickomode
email: you@example.com
description: a collection of rich thoughts from a rich boy
baseurl:  ''
url:  https://sickomode.org
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/
